// Code generated by protoc-gen-go.
// source: append_entries_request.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	append_entries_request.proto
	append_entries_responses.proto
	log_entry.proto

It has these top-level messages:
	AppendEntriesRequest
	AppendEntriesResponse
	LogEntry
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type AppendEntriesRequest struct {
	Term             *uint64     `protobuf:"varint,1,req,name=Term" json:"Term,omitempty"`
	PrevLogIndex     *uint64     `protobuf:"varint,2,req,name=PrevLogIndex" json:"PrevLogIndex,omitempty"`
	PrevLogTerm      *uint64     `protobuf:"varint,3,req,name=PrevLogTerm" json:"PrevLogTerm,omitempty"`
	CommitIndex      *uint64     `protobuf:"varint,4,req,name=CommitIndex" json:"CommitIndex,omitempty"`
	LeaderName       *string     `protobuf:"bytes,5,req,name=LeaderName" json:"LeaderName,omitempty"`
	Entries          []*LogEntry `protobuf:"bytes,6,rep,name=Entries" json:"Entries,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *AppendEntriesRequest) Reset()                    { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()               {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppendEntriesRequest) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogIndex() uint64 {
	if m != nil && m.PrevLogIndex != nil {
		return *m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if m != nil && m.PrevLogTerm != nil {
		return *m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetCommitIndex() uint64 {
	if m != nil && m.CommitIndex != nil {
		return *m.CommitIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderName() string {
	if m != nil && m.LeaderName != nil {
		return *m.LeaderName
	}
	return ""
}

func (m *AppendEntriesRequest) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*AppendEntriesRequest)(nil), "protobuf.AppendEntriesRequest")
}

var fileDescriptor0 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2c, 0x28, 0x48,
	0xcd, 0x4b, 0x89, 0x4f, 0xcd, 0x2b, 0x29, 0xca, 0x4c, 0x2d, 0x8e, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x52,
	0xfc, 0x39, 0xf9, 0xe9, 0x60, 0x45, 0x95, 0x10, 0x29, 0xa5, 0xb9, 0x8c, 0x5c, 0x22, 0x8e, 0x60,
	0xbd, 0xae, 0x10, 0xad, 0x41, 0x10, 0x9d, 0x42, 0x3c, 0x5c, 0x2c, 0x21, 0xa9, 0x45, 0xb9, 0x12,
	0x8c, 0x0a, 0x4c, 0x1a, 0x2c, 0x42, 0x22, 0x5c, 0x3c, 0x01, 0x45, 0xa9, 0x65, 0x3e, 0xf9, 0xe9,
	0x9e, 0x79, 0x29, 0xa9, 0x15, 0x12, 0x4c, 0x60, 0x51, 0x61, 0x2e, 0x6e, 0xa8, 0x28, 0x58, 0x29,
	0x33, 0x4c, 0xd0, 0x39, 0x3f, 0x37, 0x37, 0xb3, 0x04, 0xa2, 0x92, 0x05, 0x2c, 0x28, 0xc4, 0xc5,
	0xe5, 0x93, 0x9a, 0x98, 0x92, 0x5a, 0xe4, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x0a, 0x14, 0xe3, 0x14,
	0x52, 0xe6, 0x62, 0x87, 0xda, 0x29, 0xc1, 0xa6, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa4, 0x07, 0x73,
	0xa7, 0x1e, 0xd0, 0x48, 0x90, 0x5c, 0x25, 0x20, 0x00, 0x00, 0xff, 0xff, 0x93, 0x26, 0xce, 0xad,
	0xd9, 0x00, 0x00, 0x00,
}
