show databases;
show tables;
show columns from customers;
show create database 库名;
show create table 表名;
show grants;
show errors;
show warnings;
select prod_name from products;
select prod_id, prod_name, prod_price from products;
select * from products;
select DISTINCT vend_id from products;
select prod_name from products limit 5;
select prod_name from products limit 5,5;
select products.prod_name from crashcourse.products;
select prod_name from products order by prod_name;
select prod_id, prod_name, prod_price from products order by prod_price, prod_name;
select prod_id, prod_name, prod_price from products order by prod_price DESC, prod_name;
select prod_id, prod_name, prod_price from products where prod_price between 5 AND 10;
select prod_id, prod_name, prod_price from products where prod_price is null;
select prod_name, prod_price from products where (vend_id = 1002 or vend_id = 1003) and prod_price >= 10;
select prod_id, prod_name from products where prod_name like 'jet%';
select prod_id, prod_name from products where prod_name like '_ ton anvil';
select prod_name from products where prod_name REGEXP '.000' order by prod_name;
select prod_name from products where prod_name REGEXP '1000|2000' order by prod_name;
select vend_name from vendors where vend_name REGEXP '\\.' order by vend_name;
select concat(vend_name, ' (', vend_country, ')') from vendors order by vend_name;
select concat(RTrim(vend_name), ' (', RTrim(vend_country), ')') as vend_title from vendors order by vend_name;
select max(prod_price) from products;
select count(*) as num_cust from customers;
select vend_id, count(*) as num_prods from products group by vend_id;
select cust_id, count(*) as orders from orders group by cust_id having count(*) >= 2;
select cust_id, count(*) as orders from orders where prod_price >= 10 group by cust_id having count(*) >= 2;
select cust_id, count(*) as orders from orders group by cust_id having sum(quantity*item_price) >= 50 order by ordertotal;
select cust_id from orders where order_num in (select order_num from orderitems where prod_id = 'TNT2');
select cust_name, cust_state, (select count(*) from orders where orders.cust_id = customers.cust_id) as orders \
from customers order by cust_name;
select vend_name, prod_name, prod_price from vendors inner join products on vendors.vend_id = products.vend_id;
select vend_id, prod_id, prod_price from products where prod_price <= 5 union \
select vend_id, prod_id, prod_price from products where vend_id in (1001, 1002);
select note_text from productnotes where match(note_text) Against('rabbit');
insert into customers values(.......);
insert into customers select...... from custnew;
update customers set cust_name = 'nihao' cust_email = 'a@b.com' where cust_id = 10005;
delete from customers where cust_name = 10006;
alter table vendors add vend_phone char(20);
rename table customer2 to customers;
create view vendorlocation as select ......;